package de.haw.swa.ordermanagement.domain.model.customer;

import de.haw.swa.ordermanagement.domain.model.shared.AggregateRoot;
import jakarta.persistence.*;


@Entity
@Table(name = "customers")
public class Customer extends AggregateRoot<Long> {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(nullable = false)
    private String name;
    
    @Column(nullable = false, unique = true)
    private String email;
    
    @Embedded
    private Address address;
    
    protected Customer() {}
    
    public Customer(Long customerId, String name, String email, Address address) {
        this.id = customerId;
        this.name = name;
        this.email = email;
        this.address = address;
    }
    
    public Customer(String name, String email, Address address) {
        // id will be auto-generated by JPA
        this.name = name;
        this.email = email;
        this.address = address;
    }
    
    @Override
    public Long getId() {
        return id;
    }
    
    public String getName() {
        return name;
    }
    
    public String getEmail() {
        return email;
    }
    
    public Address getAddress() {
        return address;
    }
}